version: "3"

services:
  db:
    image: mysql
    container_name: MYSQL
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "Appweb"
    volumes:
      - ./schemas:/var/lib/mysql
