# Dockerfile para backend

# Usa la imagen base de Node.js versión 14
FROM node:14

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo package.json y package-lock.json (si existe)
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia todos los archivos del directorio actual al directorio de trabajo en el contenedor
COPY . .

# Expone el puerto en el que la aplicación está ejecutando
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["npm", "start"]
